triggers:
  - keyword: escalate_ticket

steps:
  - ask: What is your name?
  - user_set: name
  - ask: What is your email address?
  - user_set: email
  - ask: Leave a message and we'll get back to you shortly by email
  - flow_set: message
  - type: meya.zendesk.support.component.user.create_or_update
    integration: integration.zendesk.support
    name: (@ user.name )
    email: (@ user.email )
  - type: meya.zendesk.support.component.ticket.create
    integration: integration.zendesk.support
    subject: flow.message
    comment: (@ flow.get("comment") )
    link: true
  - say: 'Ticket #(@ flow.result.id ) created'
